### ISSUE TITLE
Network not detecting groups of nuclei

### ISSUE THREAD

**Issue by jasperblee** [spreka/biomagdsb#10]
Hello,

I have noticed that the algorithm will fail to detect clusters of nuclei, with the resulting segmentation containing large empty gaps. I have attached two representative images of this situation. Is there any way I can modify the algorithm, or pre-process my image, to prevent this from happening? Thank you!

![image](https://user-images.githubusercontent.com/32905236/90593552-37854600-e1b6-11ea-9c10-d28ae4c92e1d.png)

![image](https://user-images.githubusercontent.com/32905236/90593555-39e7a000-e1b6-11ea-922d-bd28735b62ad.png)

**Comment by spreka** [comment]
@jasperblee Thanks for reaching out and sorry for the late response. I tested your image using the presegmenter and the final model, respectively. When only using the fast prediction (without calculating resizing) it already found more nuclei. If you set the size (median size, I tested with 15), results will further improve.
As examples, please see the segmentations outlined in red, overlayed on the original image (for better visibility) below.

*fast prediction (default settings, presegmenter model):*
![90593552-37854600-e1b6-11ea-9c10-d28ae4c92e1d](https://user-images.githubusercontent.com/42864288/93077520-334f2a00-f689-11ea-890b-a5afa3dad237.png)

*fast prediction (size 15, presegmenter model)*:
![90593552-37854600-e1b6-11ea-9c10-d28ae4c92e1d](https://user-images.githubusercontent.com/42864288/93077639-5da0e780-f689-11ea-91e9-f93750db4166.png)

*fast prediction (size 15, final model)*:
![90593552-37854600-e1b6-11ea-9c10-d28ae4c92e1d](https://user-images.githubusercontent.com/42864288/93077671-714c4e00-f689-11ea-8cc4-ac4e01051e38.png)

You can run these with the bash/batch scripts
`run_workflow_predictOnly_fast_manualsize.sh . testImages`
or 
`run_workflow_predictOnly_fast_manualsize.bat . testImages`
on the default test image folder in the repo as an example, after setting the `target_object_size` parameter in `\kaggle_workflow\maskrcnn\config\predict\presegment_manualsize.json` to e.g. 15.

Let me know if you could manage to solve the clumped region-issue on your images.

**Comment by jasperblee** [comment]
Hello,

Thank you for the help! I set the target size to 15 as you said, and ran the fast prediction. One question - when I run this, the program stops running after "PRESEGMENTATION DONE". Is this the intended behavior, and the later algorithm steps that occur during the full prediction pipeline are the resizing steps that I am meant to ignore?

**Comment by spreka** [comment]
@jasperblee this `manualsize` fast prediction was only a demonstration of how you can set the size parameter. You can change the full prediction pipeline to include this instead of the default size calculation based on the presegmented masks. It is up to you whether you want to include the post-processing steps :)

**Comment by jasperblee** [comment]
@spreka  Thank you for the clarification, and for helping troubleshoot - the results are much better now!
