### ISSUE TITLE
Is there a way to return a blank image if no nuclei are detected (invalid prediction)?

### ISSUE THREAD

**Issue by jasperblee** [spreka/biomagdsb#13]
My current pipeline involves the generation of many subimages from a larger image, and these subimages are then processed using the segmentation network. However, a few of these subimages invariably do not contain any nuclei, which the segmentation program treats as invalid and does not return anything. Is there a way to make the program return the blank image in this case, so that the segmented subimages can be stitched back together even if there are no nuclei present in a subimage? Thank you so much!

**Comment by spreka** [comment]
Simply comment out the `continue` statement in the [default segmentation script](https://github.com/spreka/biomagdsb/blob/master/FinalModel/segmentation.py#L244) (line #244) or in the [manual size segmentation script](https://github.com/spreka/biomagdsb/blob/master/FinalModel/segmentation_manualsize.py#L270) (line #270) to have blank masks written.
