### ISSUE TITLE
Error during pre-segmentation

### ISSUE THREAD

**Issue by PetterRanefall** [spreka/biomagdsb#2]
I get the following error when I try to run  start_prediction_full.bat:

File "C:\Code\Python3\biomagdsb\FinalModel\\segmentation.py", line 119, in Segment
    temp, _, _ = cv2.findContours(temp, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
ERROR: "Error during pre-segmentation"

**Comment by OpenCv30** [comment]
@PetterRanefall - I am facing the same problem. Time being,  I have forced IF condition to False. Not seeing any degradation as such.

**Comment by csmolnar** [comment]
@PetterRanefall @OpenCv30  Could you please check your OpenCV version? The project requires 3.4.2.17. The earlier releases returned 2 values only.

**Comment by PetterRanefall** [comment]
I have OpenCV 4.1.1.26

**Comment by csmolnar** [comment]
The function declaration has 2 return values again in this new version:
[https://docs.opencv.org/4.1.1/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0](https://docs.opencv.org/4.1.1/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0)
Downgrading your OpenCV to the suggested version should solve your problem.

**Comment by spreka** [comment]
@PetterRanefall @OpenCv30 can you please confirm if the issue was resolved by @csmolnar's suggestion?

**Comment by PetterRanefall** [comment]
I suppose the issue is solved by downgrading, but I am not so keen on doing the downgrade.
