### ISSUE TITLE
Error for single channel grayscale images

### ISSUE THREAD

**Issue by PetterRanefall** [spreka/biomagdsb#3]
If I run start_prediction_full.bat on a single channel grayscale image I get an error:
  File "C:\Code\Python3\biomagdsb\UNet\utils.py", line 264, in __getitem__
    image = io.imread(image_path)[:, :, :3]
IndexError: too many indices for Array

and later:
Error using imread>get_full_filename (line 481)
File "C:\Code\Python3\biomagdsb\kaggle_workflow\outputs\ensemble\output\\BE_300_01_rescaled.png" does not exist.

Error in imread (line 344)
    filename = get_full_filename(fid, errmsg, filename);

Error in postProcCodeFINAL (line 104)
        probMap = (imread([probFolder filesep imageList(i).name(1:end-5) '.png']));

Error in postProcCodeRunnerFINAL (line 94)
    postProcCodeFINAL(inMainFolder,outMainFolder,...

(It works if I convert the image to RGB before starting)

**Comment by spreka** [comment]
@PetterRanefall Please take a look at `start_image_preprocessing.bat`, it converts your images to 8-bit RGB.

**Comment by PetterRanefall** [comment]
OK, thanks!

**Comment by spreka** [comment]
@PetterRanefall I am closing this now as the suggested script solves the error. Please feel free to reopen it if the issue still occurs.
