### ISSUE TITLE
What Matab tools/libraries are needed?

### ISSUE THREAD

**Issue by andersla** [spreka/biomagdsb#5]
I wanted to try your pipeline and are about to install MatLab and wonder if there are any tools needed to be installed apart from MatLab itself?

Here is the list of installation options I get:

Product | Size [MB]

MATLAB 9.6 | 4095
Simulink 9.3 | 6335
5G Toolbox 1.1 | 16
Aerospace Blockset 4.1 | 164
Aerospace Toolbox 3.1 | 211
Antenna Toolbox 4.0 | 1008
Audio Toolbox 2.0 | 291
Automated Driving Toolbox 2.0 | 521
AUTOSAR Blockset 2.0 | 256
Bioinformatics Toolbox 4.12 | 541
Communications Toolbox 7.1 | 1481
Computer Vision Toolbox 9.0 | 2030
Control System Toolbox 10.6 | 796
Curve Fitting Toolbox 3.5.9 | 52
Database Toolbox 9.1 | 48
Datafeed Toolbox 5.8.1 | 14
Deep Learning Toolbox 12.1 | 804
DSP System Toolbox 9.8 | 434
Econometrics Toolbox 5.2 | 176
Embedded Coder 7.2 | 326
Filter Design HDL Coder 3.1.5 | 13
Financial Instruments Toolbox 2.9 | 111
Financial Toolbox 5.13 | 122
Fixed-Point Designer 6.3 | 340
Fuzzy Logic Toolbox 2.5 | 44
Global Optimization Toolbox 4.1 | 48
HDL Coder 3.14 | 356
Image Acquisition Toolbox 6.0 | 61
Image Processing Toolbox 10.4 | 2877
Instrument Control Toolbox 4.0 | 36
LTE HDL Toolbox 1.3 | 42
LTE Toolbox 3.1 | 99
Mapping Toolbox 4.8 | 515
MATLAB Coder 4.2 | 76
MATLAB Compiler 7.0.1 | 602
MATLAB Compiler SDK 6.6.1 | 129
MATLAB Report Generator 5.6 | 71
Mixed-Signal Blockset 1.0 | 60
Model Predictive Control Toolbox 6.3 | 38
Optimization Toolbox 8.3 | 179
Parallel Computing Toolbox 7.0 | 950
Partial Differential Equation Toolbox 3.2 | 117
Phased Array System Toolbox 4.1 | 142
Powertrain Blockset 1.5 | 178
Predictive Maintenance Toolbox 2.0 | 104
Reinforcement Learning Toolbox 1.0 | 293
RF Blockset 7.2 | 279
RF Toolbox 3.6 | 69
Risk Management Toolbox 1.5 | 22
Robotics System Toolbox 2.2 | 490
Robust Control Toolbox 6.6 | 63
Sensor Fusion and Tracking Toolbox 1.1 | 225
SerDes Toolbox 1.0 | 21
Signal Processing Toolbox 8.2 | 1867
SimBiology 5.8.2 | 94
SimEvents 5.6 | 68
Simscape 4.6 | 122
Simscape Driveline 2.16 | 37
Simscape Electrical 7.1 | 450
Simscape Fluids 2.6 | 68
Simscape Multibody 6.1 | 723
Simulink 3D Animation 8.2 | 106
Simulink Check 4.3 | 158
Simulink Coder 9.1 | 252
Simulink Control Design 5.3 | 120
Simulink Coverage 4.3 | 37
Simulink Design Optimization 3.6 | 138
Simulink Design Verifier 4.1 | 53
Simulink Desktop Real-Time 5.8 | 94
Simulink Report Generator 5.6 | 46
Simulink Requirements 1.3 | 66
Simulink Test 3.0 | 260
Stateflow 10.0 | 119
Statistics and Machine Learning Toolbox 11.5 | 704
Symbolic Math Toolbox 8.3 | 770
System Composer 1.0 | 94
System Identification Toolbox 9.10 | 67
Text Analytics Toolbox 1.3 | 212
Trading Toolbox 3.5.1 | 12
Vehicle Dynamics Blockset 1.2 | 125
Wavelet Toolbox 5.2 | 118
WLAN Toolbox 2.1 | 21

**Comment by spreka** [comment]
@andersla We use the following toolboxes (versions for R2017a/b):
Image Processing Toolbox
Parallel Computing Toolbox
Statistics and Machine Learning Toolbox
Curve Fitting Toolbox
Global Optimization Toolbox
Optimization Toolbox

Please let me know if this list proves to be insufficient.
As a side note, for general usability I usually install all available toolboxes.

**Comment by andersla** [comment]
I can confirm that in the end the only packages needed were:
Image Processing Toolbox
Parallel Computing Toolbox

**Comment by spreka** [comment]
@andersla thank you. The others I listed are used by the training and post-processing parameter search pipelines.
