### ISSUE TITLE
Error in cell size estimation and getting black images as presegmentation ends

### ISSUE THREAD

**Issue by ErfanMN** [spreka/biomagdsb#6]
Hi, I Wanted to run start_prediction_full.sh and follow all the instructions in the documentation and github readme. the first part presegmentation started and ends and next part cell size estimation failed with just this error : 

CELL SIZE ESTIMATION:
ERROR: Error during cell size estimation

after this I went to check presegment output and all I see was black images. what is going wrong ?? How can I find out where is my problem ??

**Comment by spreka** [comment]
@ErfanMN thanks for your feedback. This step calls a Matlab command that performs the cell size estimation, and if any error occurs, should print some Matlab stack about it. Do you see the Matlab "header" (like below) when this part of the pipeline starts executing?
```
          < M A T L A B (R) >
Copyright 1984-2018 The MathWorks, Inc.
 R2018b (9.5.0.944444) 64-bit (glnxa64)
            August 28, 2018
```
If so, can you post the error?

The output in folder `presegment` is 16-bit multi-labelled .tiff format. You need a proper image viewer software to display it correctly, e.g. Fiji or Irfanview (Windows-only), default viewers indeed display it as full black. Can you verify that the masks in folder `/kaggle_workflow/inputs/train_maskrcnn/masks/` (the same format) can be displayed correctly i.e. you see the nuclei in different gray intensities?

**Comment by ErfanMN** [comment]
Thanks for your responding. I check the presegment folder and the black images. you are right that was because of the viewer. I download Irfanview and can see the segmented images now. 

for the first part I download and install matlab in linux. first time I ran the pipeline it says :
matlab: command not found
but after I run this command it passed. 
export PATH=/path/to/MATLAB/bin/:$PATH

now the terminal figure out matlab command but I did not see matlab header !! 
and it just return 

CELL SIZE ESTIMATION:
ERROR: Error during cell size estimation.

as you said maybe it is because of my matlab. I'll check my matlab installation ASAP. and comeback to you.

**Comment by spreka** [comment]
@ErfanMN can try running this command in terminal?
`matlab -nodisplay -nodesktop -nosplash -nojvm -r "for i=1:10 disp(i); end; exit;"`
It should print numbers 1-10 then exit. If you change `i` to `k` it should print an error that `k` does not exist.

What are your Matlab and os versions?

**Comment by ErfanMN** [comment]
Thanks @spreka . you were right. it was my matlab installation problem. actually at first I was running the pipeline in linux subsystem in windows 10. and linux version of matlab not working correctly there. Now I'm running the pipeline in linux ubuntu 16.04 and it works succesfully. my matlab version is 2018a.

**Comment by spreka** [comment]
@ErfanMN glad to see you could work it out
