### ISSUE TITLE
training after style transfer

### ISSUE THREAD

**Issue by ErfanMN** [spreka/biomagdsb#7]
Hi , again.
you wrote in the readme file that (single style transfer section): 
After this you are ought to run these training scripts instead of the ones above:

start_prediction_fast.bat (Windows)
start_prediction_fast.sh (Linux)

but, these scripts are for predictions. they should not be train scripts ?? or am I missing something ? 
as I know we should train the models again with new augmented data after style transfer. correct me if I'm wrong.

**Comment by spreka** [comment]
@ErfanMN thank you for pointing this out, I fixed the script names in the README
