### ISSUE TITLE
Error in training UNET

### ISSUE THREAD

**Issue by ErfanMN** [spreka/biomagdsb#8]
hi , again. 
I can run prediction_full and other scripts in your repo. but I got this error for start_training.sh file for training UNET. 

CELL SIZE ESTIMATION ON VALIDATION DONE
INIT UNET ENVIRONMENT:
INIT UNET ENVIRONMENT DONE
UNET TRAIN MODELS:
UNET TRAIN MODELS:
PREDICT UNet_sigma0.0_1 MODEL:
./kaggle_workflow/unet
./kaggle_workflow/outputs/train_unet
./kaggle_workflow/outputs/test1
./kaggle_workflow/outputs
/media/erfan/3AB81DDCB81D9809/Thesis/Projects/Style_project/main/biomagdsb/venv/lib/python3.7/site-packages/skimage/util/dtype.py:503: UserWarning: Downcasting uint16 to uint8 without scaling because max value 255 fits in uint8
  return _convert(image, np.uint8, force_copy)
Traceback (most recent call last):
  File "./UNet/train_sh.py", line 58, in <module>
    model.train_model(train_dataset, n_epochs=args.epochs, n_batch=args.batch, verbose=args.verbose, validation_dataset=val_dataset)
  File "/media/erfan/3AB81DDCB81D9809/Thesis/Projects/Style_project/main/biomagdsb/UNet/wrappers.py", line 54, in train_model
    epoch_running_loss += training_loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
ERROR: Error during unet prediction

Can You help me with this ?? 
I ran the code on ubuntu 16.04 and matlab 2018a version, if you need.

Thanks

**Comment by spreka** [comment]
@ErfanMN thank you for pointing this out. A related pytorch version issue was already mentioned in the documentation, I just extended it with this for U-Net. If you have torch>0.5 please follow instructions there. Let me know if it helped

**Comment by spreka** [comment]
@ErfanMN if this is still an issue, feel free to re-open it
