### ISSUE TITLE
Extracting nucleus size/location data from final output?

### ISSUE THREAD

**Issue by jasperblee** [spreka/biomagdsb#9]
I've set up the pipeline to run on my own images, and successfully obtained the final segmentation images. Now, I want to extract the data for nucleus size and location for downstream analysis - ideally in .csv or similar format. I was just wondering if the pipeline includes this data somewhere in the output folders? Thank you!

**Comment by spreka** [comment]
@jasperblee you can extract the median nucleus size measurement from your final segmentation masks using e.g. `\matlab_scripts\cellSizeEstimateForPrediction\estimateCellSizeFromMask.m` which is used to estimate nucleus size in the full prediction pipeline, in `\matlab_scripts\cellSizeEstimateForPrediction\cellSizeDataGenerate.m`; you can modify the latter to only print the object sizes to .csv. Locations can also be fetched from `regionprops`:
```
props = regionprops(maskImg, 'EquivDiameter','Centroid'); 
allSize = [props.EquivDiameter];
allLoc = cell2mat(arrayfun(@(x) x.Centroid,props,'UniformOutput',false))';
```
This will return the sizes and the locations in 1xn and 2xn matrices.

The pipeline only returns .csv-s of the tensor sizes calculated from median object sizes for each image.

**Comment by jasperblee** [comment]
Great, thank you for the help!
